# MIT License

# Copyright (c) 2022 Ai4Energy Team of Xi'an Jiaotong Universiy

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3"

services:
  mongo:
    build:
      context: ./mongo/
      dockerfile: ./Dockerfile
    image: metapse/mongo:1.0.0
    container_name: metapse-mongo
    hostname: metapse-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
      - mongo_config:/data/configdb
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "20"

  juliaapi:
    build:
      context: ./juliaapi
      dockerfile: ./Dockerfile
    image: metapse/juliaapi:1.0.0
    container_name: metapse-juliaapi
    hostname: metapse-juliaapi
    restart: always
    command: julia --project=/opt/juliaapi http.jl
    ports:
      - "8080:8080"
    volumes:
      - juliaapi:/opt/juliaapi

  metapse-web:
    build:
      context: ./metapseweb
      dockerfile: ./Dockerfile
    image: metapse/web:1.0.0
    container_name: metapse-web
    hostname: metapse-web
    restart: always
    ports:
      - "80:80"
      - "413:413"
    volumes:
      - metapseweb:/usr/share/nginx/html

volumes:
  mongo_config:
  mongo_db:
  juliaapi:
  metapseweb:

networks:
  metapsenet:
    driver: "bridge"
