# MIT License

# Copyright (c) 2022 Ai4Energy Team of Xi'an Jiaotong Universiy

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3"

services:
  mongo:
    image: mongo:6.0.2
    container_name: metapse-mongo
    hostname: metapse-mongo
    restart: always
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo_db:/data/db
      - ./mongo/mongo_config:/data/configdb
      - ./mongo/mongo-entrypoint:/docker-entrypoint-initdb.d
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "20"
    networks:
      - metapsenet

networks:
  metapsenet:
    driver: "bridge"
